name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  terraform:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Terraform FMT
        if: github.event_name == 'pull_request'
        run: terraform fmt -recursive

      - name: Terraform Validate
        if: github.event_name == 'pull_request'
        run: |
          terraform init -backend=false
          terraform validate

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        env:
          TF_VAR_subnets: ${{ secrets.SUBNET_ID }}
        run: |
          terraform init -backend-config="bucket=${{ secrets.BUCKET_NAME }}"
          terraform plan

      - name: Terraform Apply
        if: github.event_name == 'push'
        env:
          TF_VAR_subnets: ${{ secrets.SUBNET_ID }}
        run: |
          terraform init -backend-config="bucket=${{ secrets.BUCKET_NAME }}"
          terraform apply -auto-approve