name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: Terraform FMT
        run: terraform fmt -recursive

      # Runs a set of commands using the runners shell
      - name: Terraform Validate
        run: |
          terraform init -backend=false
          terraform validate
